FROM alpine:latest
MAINTAINER Jerry <mcchae@gmail.com>

RUN apk update && apk add tftp-hpa tcpdump && \
    mkdir -p /data

EXPOSE 69/udp
VOLUME /data

# ENTRYPOINT ["in.tftpd"]

CMD ["in.tftpd", "-L", "-vvv", "-u", "root", "--secure", "--create", "/data"]
