version: '2'

services:
  tftp:
    image: mcchae/tftp-server
    container_name: tftp_server
    ports:
    - "6969:69/udp"
    volumes:
    - ${PWD}/dhv/tftp:/data
  tftptest:
    image: mcchae/tftp-server
    container_name: tftp_client
    links:
    - tftp
    command: /bin/sleep 1000
  tftptest2:
    image: ubuntu
    container_name: tftp_client2
    links:
    - tftp
    command: sleep 1000

